# Generated by Django 2.2.5 on 2020-02-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=1024)),
                ('extra_money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('product', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('option', models.ManyToManyField(blank=True, related_name='items', to='items.Option')),
                ('tag', models.ManyToManyField(blank=True, related_name='items', to='items.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
