# Generated by Django 2.2.5 on 2020-02-22 13:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200222_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='test',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
