# Generated by Django 2.2.5 on 2020-02-22 13:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200222_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
