# Generated by Django 2.2.5 on 2020-04-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200407_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
