# Generated by Django 2.2.5 on 2020-04-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='items.Item'),
            preserve_default=False,
        ),
    ]
