# Generated by Django 2.2.5 on 2020-04-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200408_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option_name',
            new_name='name',
        ),
    ]
