# Generated by Django 2.2.5 on 2020-04-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200408_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='host',
        ),
    ]
