# Generated by Django 2.2.5 on 2020-04-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200428_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='host',
            new_name='owner',
        ),
    ]
