# Generated by Django 2.2.5 on 2020-04-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200407_2142'),
        ('reviews', '0002_recomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='items.Item'),
            preserve_default=False,
        ),
    ]
