# Generated by Django 2.2.5 on 2020-04-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200408_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='item',
            new_name='review',
        ),
    ]
