# Generated by Django 2.2.5 on 2020-04-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_thumbnail'),
        ('lists', '0002_auto_20200305_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='option',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='name',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderlists', to='items.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='status',
            field=models.CharField(choices=[('주문 접수', '주문 접수'), ('처리 중', '처리 중'), ('배송 준비중', '배송 준비중'), ('배송중', '배송중'), ('배송 완료', '배송 완료'), ('취소', '취소')], default='주문 접수', max_length=50),
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
