# Generated by Django 2.2.5 on 2020-02-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('boardbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.BoardBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('boards.boardbasemodel',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('boardbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.BoardBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('boards.boardbasemodel',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('boardbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.BoardBaseModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('boards.boardbasemodel',),
        ),
    ]
