# Generated by Django 2.2.5 on 2020-02-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200219_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='boards.Answer'),
        ),
    ]
