# Generated by Django 2.2.5 on 2020-02-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_photo_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='board_photos'),
        ),
    ]
