# Generated by Django 2.2.5 on 2020-02-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200219_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
