# Generated by Django 2.2.5 on 2020-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
