# Generated by Django 2.2.5 on 2020-02-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200219_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='boards.Notice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='boards.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='boards.Review'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='boards.Answer'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='boards.Notice'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='boards.Question'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='boards.Review'),
        ),
    ]
