# Generated by Django 2.2.5 on 2020-02-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20200219_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
