# Generated by Django 2.2.5 on 2020-04-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0002_auto_20200305_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_status',
            field=models.CharField(choices=[('미답변', '미답변'), ('답변완료', '답변완료')], default='미답변', max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qnas.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
