# Generated by Django 2.2.5 on 2020-06-07 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0008_auto_20200428_2101'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderingitems', to='items.Item')),
                ('option', models.ManyToManyField(blank=True, related_name='orderingitems', to='items.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('order_created', 'order_created'), ('wait_confirm', 'wait_confirm'), ('pay_confirmed', 'pay_confirmed'), ('pay_canceled', 'pay_canceled'), ('started_shipping', 'started_shipping'), ('ended_shipping', 'ended_shipping')], default='order_created', max_length=50)),
                ('receipt_id', models.CharField(blank=True, max_length=24)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=7)),
                ('confirmed_date', models.DateTimeField(blank=True)),
                ('shipping_started_date', models.DateTimeField(blank=True)),
                ('completed_date', models.DateTimeField(blank=True)),
                ('items', models.ManyToManyField(related_name='orders', to='orders.OrderingItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
